Topsis method

In [19]:
import numpy as np

In [20]:
A = np.array([[595,0.35,3,3,0.045],[1119,0,3,3,0.059],[311,0.27,7,3,0.021],[311,0.16,7,3,0.032],[520,0.04,3,5,0.024],[905,0.2,3,5,0.032],[2226,0.61,5,5,0.025],[311,0.06,7,5,0.021],[2576,1,5,7,0.024],[514,0,5,7,0]])

In [21]:
print(A)

[[5.950e+02 3.500e-01 3.000e+00 3.000e+00 4.500e-02]
 [1.119e+03 0.000e+00 3.000e+00 3.000e+00 5.900e-02]
 [3.110e+02 2.700e-01 7.000e+00 3.000e+00 2.100e-02]
 [3.110e+02 1.600e-01 7.000e+00 3.000e+00 3.200e-02]
 [5.200e+02 4.000e-02 3.000e+00 5.000e+00 2.400e-02]
 [9.050e+02 2.000e-01 3.000e+00 5.000e+00 3.200e-02]
 [2.226e+03 6.100e-01 5.000e+00 5.000e+00 2.500e-02]
 [3.110e+02 6.000e-02 7.000e+00 5.000e+00 2.100e-02]
 [2.576e+03 1.000e+00 5.000e+00 7.000e+00 2.400e-02]
 [5.140e+02 0.000e+00 5.000e+00 7.000e+00 0.000e+00]]


In [22]:
A1 = A*A

In [23]:
print(A1)

[[3.540250e+05 1.225000e-01 9.000000e+00 9.000000e+00 2.025000e-03]
 [1.252161e+06 0.000000e+00 9.000000e+00 9.000000e+00 3.481000e-03]
 [9.672100e+04 7.290000e-02 4.900000e+01 9.000000e+00 4.410000e-04]
 [9.672100e+04 2.560000e-02 4.900000e+01 9.000000e+00 1.024000e-03]
 [2.704000e+05 1.600000e-03 9.000000e+00 2.500000e+01 5.760000e-04]
 [8.190250e+05 4.000000e-02 9.000000e+00 2.500000e+01 1.024000e-03]
 [4.955076e+06 3.721000e-01 2.500000e+01 2.500000e+01 6.250000e-04]
 [9.672100e+04 3.600000e-03 4.900000e+01 2.500000e+01 4.410000e-04]
 [6.635776e+06 1.000000e+00 2.500000e+01 4.900000e+01 5.760000e-04]
 [2.641960e+05 0.000000e+00 2.500000e+01 4.900000e+01 0.000000e+00]]


In [24]:
B = np.sqrt(np.sum(A1 , axis=0))

In [25]:
print(B)

[3.85237875e+03 1.27996094e+00 1.60623784e+01 1.52970585e+01
 1.01059388e-01]


In [26]:
b1 = B[0]
b2 = B[1]
b3 = B[2]
b4 = B[3]
b5 = B[4]

In [27]:
M1 = (1-A[:,0]/b1)
M2 = (A[:,1]/b2)
M3 = (A[:,2]/b3)
M4 = (A[:,3]/b4)
M5 = (A[:,4]/b5)

print(M1)
print(M2)
print(M3)
print(M4)
print(M5)

[0.84554997 0.70953012 0.91927066 0.91927066 0.86501846 0.76508021
 0.42217519 0.91927066 0.33132224 0.86657594]
[0.27344585 0.         0.21094394 0.12500381 0.03125095 0.15625477
 0.47657704 0.04687643 0.78127384 0.        ]
[0.18677184 0.18677184 0.43580096 0.43580096 0.18677184 0.18677184
 0.3112864  0.43580096 0.3112864  0.3112864 ]
[0.19611614 0.19611614 0.19611614 0.19611614 0.32686023 0.32686023
 0.32686023 0.32686023 0.45760432 0.45760432]
[0.44528273 0.58381513 0.20779861 0.31664549 0.23748412 0.31664549
 0.24737929 0.20779861 0.23748412 0.        ]


In [28]:
W1 = 0.25*(1-A[:,0]/b1)
W2 = 0.15*(A[:,1]/b2)
W3 = 0.25*(A[:,2]/b3)
W4 = 0.20*(A[:,3]/b4)
W5 = 0.15*(A[:,4]/b5)

print(W1)
print(W2)
print(W3)
print(W4)
print(W5)

[0.21138749 0.17738253 0.22981766 0.22981766 0.21625462 0.19127005
 0.1055438  0.22981766 0.08283056 0.21664399]
[0.04101688 0.         0.03164159 0.01875057 0.00468764 0.02343822
 0.07148656 0.00703146 0.11719108 0.        ]
[0.04669296 0.04669296 0.10895024 0.10895024 0.04669296 0.04669296
 0.0778216  0.10895024 0.0778216  0.0778216 ]
[0.03922323 0.03922323 0.03922323 0.03922323 0.06537205 0.06537205
 0.06537205 0.06537205 0.09152086 0.09152086]
[0.06679241 0.08757227 0.03116979 0.04749682 0.03562262 0.04749682
 0.03710689 0.03116979 0.03562262 0.        ]


In [29]:
W1_MAX = W1.max()
W2_MAX = W2.max()
W3_MAX = W3.max()
W4_MAX = W4.max()
W5_MAX = W5.max()

print(W1_MAX)
print(W2_MAX)
print(W3_MAX)
print(W4_MAX)
print(W5_MAX)

0.22981766458253225
0.1171910764424039
0.10895024111382082
0.09152086306448588
0.0875722694653991


In [30]:
W1_MIN = W1.min()
W2_MIN = W2.min()
W3_MIN = W3.min()
W4_MIN = W4.min()
W5_MIN = W5.min()

print(W1_MIN)
print(W2_MIN)
print(W3_MIN)
print(W4_MIN)
print(W5_MIN)

0.08283055937171402
0.0
0.046692960477351775
0.03922322702763681
0.0


In [31]:
V1 = W1-W1_MAX
V2 = W2-W2_MAX
V3 = W3-W3_MAX
V4 = W4-W4_MAX
V5 = W5-W5_MAX

x1 = V1**2
x2 = V2**2
x3 = V3**2
x4 = V4**2
x5 = V5**2

H  = np.array ([x1 , x2 , x3 , x4 , x5])

d1 = np.sqrt (np.sum ( H , axis=0 ))

print(d1)

[0.11482593 0.15196777 0.11504346 0.11845513 0.14177262 0.12822359
 0.14741914 0.12649166 0.15897474 0.15015055]


In [32]:
V1_2 = W1-W1_MIN
V2_2 = W2-W2_MIN
V3_2 = W3-W3_MIN
V4_2 = W4-W4_MIN
V5_2 = W5-W5_MIN

x1_2 = V1_2**2
x2_2 = V2_2**2
x3_2 = V3_2**2
x4_2 = V4_2**2
x5_2 = V5_2**2

H2 = np.array ([x1_2 , x2_2 , x3_2 , x4_2 , x5_2])

d2 = np.sqrt (np.sum ( H2 , axis=0 ))

print(d2)

[0.15056725 0.12887582 0.16569226 0.16759687 0.1406296  0.12348353
 0.09303705 0.16488158 0.13677264 0.14700363]


In [33]:
CL = d2/(d2+d1)

In [34]:
print(CL)

[0.56733654 0.45888824 0.59020726 0.58589652 0.49797626 0.49058419
 0.38691893 0.56587757 0.46246441 0.4947049 ]
